### ISSUE TITLE
Other suits have clipping issues after using the Hololive models

### ISSUE THREAD

**Issue by ReNForce72** [Ryan-Brosius/Hololive_LethalCompany_ModelReplacements#1]
I think it might just be something with the model replacement API, but once you use one of these suits, if you switch to a suit from a different pack (in my experience, its been the ODST suit, Bocchi suit, and One Piece suits), there will be model clipping with the camera. Possibly bc the Model replacement API does something with the in game camera placement? Just wanted to make you aware if you weren't already. So far though, the mod's been great otherwise!

**Comment by Ryan-Brosius** [comment]
Yeah, it's a problem with the API, they should have changed it today to work properly now :)
Ill test it tomorrow with the hololive models, if its not working Ill try to fix it myself
