### ISSUE TITLE
Liltoons shader makes the characters lighting broken

### ISSUE THREAD

**Issue by ZarkiTabibito** [Ryan-Brosius/Hololive_LethalCompany_ModelReplacements#3]
as title, latest version (1.2.0)
![image](https://github.com/Ryan-Brosius/Hololive_LethalCompany_ModelReplacements/assets/87509561/b49758cb-77ed-46fc-86be-6a9b7a8c6532)

**Comment by Ryan-Brosius** [comment]
Will work on a fix tomorrow

**Comment by Ryan-Brosius** [comment]
Will try a bunch of different configurations to see if I can get liltoon to work, though it seems like it isn't really meant to be used in dark settings. If I can't get it to work I will consider using Units toon shader

**Comment by Ryan-Brosius** [comment]
Did a quick fix for right now using HDRP shaders, not sure I will be able to get liltoon shaders to work but Ill try these next few days. Thanks again for putting in the issue request!
