### ISSUE TITLE
Method to load multiple models

### ISSUE THREAD

**Issue by LazerguiY** [Ryan-Brosius/Hololive_LethalCompany_ModelReplacements#4]
I made my own mod to add a model replacement and it worked without issues. But I could not figure how to load multiple models in a single mod. If you don't mind me asking, what methods have you used to achieve that?

**Comment by Ryan-Brosius** [comment]
I used the moresuits mod to achieve this. If you download my mod directly from thunderstore and open it up you should be able to see the structure to use it yourself. They also have their documentation here https://github.com/x753/Lethal-Company-More-Suits if you want to take a look
